# based on v11
CHAR_MAP:
  DIR: /checkpoint/jinghuang/multiplexer/charmap/public/v3/
DATALOADER:
  ASPECT_RATIO_GROUPING: false
  NUM_WORKERS: 4
  SIZE_DIVISIBILITY: 32
DATASETS:
  AUG: false
  IGNORE_DIFFICULT: false
  MAX_ROTATE_THETA: 90
INPUT:
  MAX_SIZE_TEST: 4000
  MAX_SIZE_TRAIN: 2333
  MIN_SIZE_TEST: 1000
  MIN_SIZE_TRAIN: (800, 1000, 1200, 1400)
MODEL:
  BACKBONE:
    CONV_BODY: R-50-FPN
    OUT_CHANNELS: 256
  CHAR_MASK_ON: false
  LANGUAGE_GROUPER:
    NAME: MultiV0LanguageGrouper  # main change in this config (vs v2)
  LANGUAGE_HEAD:
    NUM_CLASSES: 8
    PREDICTOR: V1LanguagePredictor
    INPUT_H: 32
    INPUT_W: 32
    INPUT_C: 256
    CONV1_C: 64
    CONV2_C: 32
  MASK_ON: true
  META_ARCHITECTURE: GeneralizedRCNN
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: FPN2MLPFeatureExtractor
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: (0.25,)
    PREDICTOR: FPNPredictor
    USE_MASKED_FEATURE: true
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    USE_FPN: true
  ROI_MASK_HEAD:
    CHAR_NUM_CLASSES: 37
    FEATURE_EXTRACTOR: MaskRCNNFPNFeatureExtractor
    MASK_BATCH_SIZE_PER_IM: 48
    NAME: "V1ROIMaskHead"  # main change in this config (vs v2)
    POOLER_RESOLUTION: 14
    POOLER_RESOLUTION_H: 32
    POOLER_RESOLUTION_W: 32
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: (0.25,)
    PREDICTOR: GroupedMaskRCNNC4Predictor  # main change in this config (vs v2)
    RESOLUTION: 28
    RESOLUTION_H: 64
    RESOLUTION_W: 64
    SHARE_BOX_FEATURE_EXTRACTOR: false
    USE_MASKED_FEATURE: true
    USE_WEIGHTED_CHAR_MASK: true
  RPN:
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    FPN_POST_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TRAIN: 2000
    USE_FPN: true
  SEG:
    BINARY_THRESH: 0.1
    BOX_THRESH: 0.1
    EXPAND_RATIO: 3.0
    MIN_SIZE: 5
    SHRINK_RATIO: 0.4
    TOP_N_TEST: 1000
    TOP_N_TRAIN: 1000
    USE_FPN: true
    USE_FUSE_FEATURE: true
  SEG_ON: true
SEQUENCE:
  ANY:
    EMBED_SIZE: 400
    HIDDEN_SIZE: 512
    NUM_CHAR: 9000
  ANY1:
    ARCH: ctc_a  # main change in this config (vs v11)
    EMBED_SIZE: 200
    HIDDEN_SIZE: 256
    NUM_CHAR: 9000
  ANY2:
    ARCH: ctc_a  # main change in this config (vs v11)
    EMBED_SIZE: 200
    HIDDEN_SIZE: 256
    NUM_CHAR: 9000
  ANY3:
    ARCH: ctc_a  # main change in this config (vs v11)
    EMBED_SIZE: 200
    HIDDEN_SIZE: 256
    NUM_CHAR: 9000
  ANY4:
    ARCH: ctc_a  # main change in this config (vs v11)
    EMBED_SIZE: 200
    HIDDEN_SIZE: 256
    NUM_CHAR: 9000
  ANY5:
    ARCH: ctc_a  # main change in this config (vs v11)
    EMBED_SIZE: 200
    HIDDEN_SIZE: 256
    NUM_CHAR: 9000
  ANY6:
    ARCH: ctc_a  # main change in this config (vs v11)
    EMBED_SIZE: 200
    HIDDEN_SIZE: 256
    NUM_CHAR: 9000
  ANY7:
    ARCH: ctc_a  # main change in this config (vs v11)
    EMBED_SIZE: 200
    HIDDEN_SIZE: 256
    NUM_CHAR: 9000
  ARABIC:
    EMBED_SIZE: 100
    HIDDEN_SIZE: 224
    NUM_CHAR: 80
  BENGALI:
    EMBED_SIZE: 100
    HIDDEN_SIZE: 224
    NUM_CHAR: 110
  BOS_TOKEN: 0
  CHINESE:
    EMBED_SIZE: 200
    HIDDEN_SIZE: 224
    NUM_CHAR: 5200
  DEVANAGARI:
    EMBED_SIZE: 100
    HIDDEN_SIZE: 224
    NUM_CHAR: 110
  HANGUL:
    EMBED_SIZE: 200
    HIDDEN_SIZE: 224
    NUM_CHAR: 1500
  JAPANESE:
    EMBED_SIZE: 200
    HIDDEN_SIZE: 224
    NUM_CHAR: 2300
  LANGUAGES:
  - ar
  - bn
  - hi
  - ja
  - ko
  - la
  - zh
  - symbol
  LANGUAGES_ENABLED:
  - ar
  - bn
  - hi
  - ja
  - ko
  - la
  - zh
  - symbol
  LANGUAGES_UNFREEZED:
  - ar
  - bn
  - hi
  - ja
  - ko
  - la
  - zh
  - symbol
  LATIN:
    EMBED_SIZE: 150
    HIDDEN_SIZE: 256
    NUM_CHAR: 250
  MAX_LENGTH: 32
  NUM_CHAR: 36
  NUM_SEQ_HEADS: 8
  RESIZE_HEIGHT: 16
  RESIZE_WIDTH: 64
  SEQ_ON: true
  SYMBOL:
    EMBED_SIZE: 30
    HIDDEN_SIZE: 64
    NUM_CHAR: 60
  TEACHER_FORCE_RATIO: 1.0
SOLVER:
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 5000
  DISPLAY_FREQ: 20
  IMS_PER_BATCH: 8
  MAX_ITER: 100000
  RESUME: false
  STEPS: (60000, 120000)
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0001
TEST:
  CHAR_THRESH: 192
  IMS_PER_BATCH: 1
  VIS: true